### ISSUE TITLE
Contacts without prefecture data from LOTW are skipped

### ISSUE THREAD

**Issue by sardonyxserendil** [kilo8deltapapa/wajalist#2]
Hello and thank you for this tool!  When I started working on WAJA nothing like this existed, so I resorted to using excel documents. Dumping my data from LOTW and inputting it into this tool resulted in me missing 12 prefectures.  However, my Excel document I've been tracking this in says I'm missing 9 prefectures.  I believe the problem lies within the LOTW data and if it has prefecture listed or not.  I think rather than skipping over data that doesn't have prefecture listed the tool should output an "error log" or notify the user that some contacts could not be mapped to a prefecture and they should manually investigate - otherwise some people might have contacts in prefectures they already have and not know it.

I'll attach screenshots that hopefully clarify this problem.
![not_work](https://github.com/kilo8deltapapa/wajalist/assets/9355932/bf2ff4b1-02c5-469d-a336-7a90ee434c82)
![works](https://github.com/kilo8deltapapa/wajalist/assets/9355932/d6e1d51a-429e-478a-b862-b711b6a4b3a6)

**Comment by sardonyxserendil** [comment]
Looking into this a bit more, the adi file from LOTW on contacts that are not mapping correctly have no "State" data.  Screenshot attached.  I'm not sure what other peoples logs look like, but my ADI file from LOTW has about 1/3 of the contacts with this column blank.  I'm assuming the state column is being mapped to the prefecture number.
![nostate](https://github.com/kilo8deltapapa/wajalist/assets/9355932/5d1d274b-169a-4643-9338-22fb49970fcb)

**Comment by kilo8deltapapa** [comment]
The issue here is that the WAJA award requires proof of contact.  If the prefecture is not listed in LoTW then it cannot be verified.  The best solution here is to reach out to the JA station(s) and ask them to re-upload their log with the prefecture.  A list of JA QSL's without prefectures could be generated by this script for this purpose.    

The JARL rules (#3) state, "Each list must be accompanied by a statement of the applicant himself/herself making an oath that the QSL cards of the contacts listed are in the possession of the applicant and that the items of the cards are correctly listed."   It is not a stretch to believe that the same would apply to LoTW QSL records, so having a record w/the necessary data (prefecture) listed seems imperative.

**Comment by sardonyxserendil** [comment]
I agree then the script might make a list of contacts without prefectures so the user is aware they might want to contact those stations and have the contact reuploaded (or manually investigated at least to see if they need their listed prefecture).  In my case it makes a big difference as I have 3 contacts without prefectures that I was (incorrectly) thinking I could use their home prefecture listed on their address as proof of contact of that prefecture.

**Comment by kilo8deltapapa** [comment]
Will add a listing of QSL records that are missing prefecture; callsign and date of QSO will be saved to missing.csv.
